spring.datasource.url=jdbc:mysql://zephyr.proxy.rlwy.net:39024/mysql
spring.datasource.username=root
spring.datasource.password=qKCBNJGglRQxbLTebIdgCCgsvnjSjsDb
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect