spring.application.name=prestamosportatil


spring.datasource.url=jdbc:mysql://localhost:3306/prestamos_portatiles_test
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect